name: E2E Test CI

on:
  push:
    branches:
      - trunk
      - release-*

  pull_request:
    branches:
      - trunk

  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.name }} binaries
    runs-on: ${{ matrix.runner }}
    env:
      GOVER: 1.22
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch_go }}

    strategy:
      matrix:
        include:
          # - name: Linux x64
          #   binary: linux-x64
          #   runner: rust
          #   target_os: linux
          #   target_arch: x86_64
          #   target_arch_go: amd64
          - name: macOS aarch64 (Apple Silicon)
            binary: macos-x64
            runner: macos-14
            target_os: darwin
            target_arch: aarch64
            target_arch_go: arm64
          # - name: macOS x64 (Intel)
          #   runner: rust-osx-x64
          #   target_os: darwin
          #   target_arch: x86_64
          #   target_arch_go: amd64
          # - name: Windows x64
          #   runner: rust-windows-x64
          #   target_os: windows
          #   target_arch: x86_64
          #   target_arch_go: amd64

    steps:
      - id: build
        name: Build binaries
        run: |
          mkdir -p artifacts/${{ matrix.binary }}
          touch artifacts/${{ matrix.binary }}/spice.txt
          echo "binaries: ${{ matrix.binary }}-binaries" >> artifacts/${{ matrix.binary }}/spice.txt

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.binary }}
          path: artifacts/${{ matrix.binary }}

  test_qyuckstart_dremio:
    name: "E2E Test: Dremio quickstart, using ${{ matrix.binary }}"
    runs-on: ${{ matrix.runner }}
    needs: build

    strategy:
      matrix:
        include:
          - name: macOS aarch64 (Apple Silicon)
            binary: macos-x64
            runner: macos-14

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries-${{ matrix.binary }}
          path: binaries

      - name: Install spice (TEMP)
        run: |
          curl https://install.spiceai.org | /bin/bash
          echo "$HOME/.spice/bin" >> $GITHUB_PATH
        shell: bash

      - name: Check spice version
        run: spice version

      - name: Init spice app
        run: |
          # TODO
          mkdir test_app && cd test_app
          spice init test_app

      - name: Connect Dremio
        working-directory: test_app
        run: |
          spice login dremio -u demo -p demo1234

      - name: Start spice runtime
        working-directory: test_app
        run: |
          spice run &

      - name: Wait for Spice runtime healthy
        working-directory: test_app
        timeout-minutes: 1
        run: |
          while [[ "$(curl -s http://localhost:3000/health)" != "ok" ]]; do sleep 1; done

      - name: Add spiceai/quickstart
        working-directory: test_app
        run: |
          spice add spiceai/quickstart
          cat spicepod.yaml

      - name: Check datasets
        working-directory: test_app
        run: |
          curl http://localhost:3000/v1/datasets | jq

  # test_qyuckstart_spiceai:
  #   name: "E2E Test: Spiceai quickstart, using ${{ matrix.binary }}"
  #   runs-on: ${{ matrix.runner }}
  #   needs: build

  #   strategy:
  #     matrix:
  #       include:
  #         - name: macOS aarch64 (Apple Silicon)
  #           binary: macos-x64
  #           runner: macos-14

  #   steps:
  #     - name: Download binaries
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: binaries-${{ matrix.binary }}
  #         path: binaries

  #     - name: Run tests
  #       run: |
  #         echo "Running test_1 on ${{ matrix.binary }}"
  #         ls -la ./
