name: E2E Test CI

on:
  push:
    branches:
      - trunk
      - release-*

  pull_request:
    branches:
      - trunk

  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.name }} binaries
    runs-on: ${{ matrix.runner }}
    env:
      GOVER: 1.22
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch_go }}

    strategy:
      matrix:
        include:
          - name: Linux x64
            binary: linux-x64
            runner: rust
            target_os: linux
            target_arch: x86_64
            target_arch_go: amd64
          - name: macOS aarch64 (Apple Silicon)
            binary: macos-x64
            runner: macos-14
            target_os: darwin
            target_arch: aarch64
            target_arch_go: arm64
          # - name: macOS x64 (Intel)
          #   runner: rust-osx-x64
          #   target_os: darwin
          #   target_arch: x86_64
          #   target_arch_go: amd64
          # - name: Windows x64
          #   runner: rust-windows-x64
          #   target_os: windows
          #   target_arch: x86_64
          #   target_arch_go: amd64

    steps:
      - id: build
        name: Build binaries
        run: |
          echo "build"
          touch ${{ matrix.binary }}-bin.txt
          echo "binaries: ${{ matrix.binary }}-binaries" >> ${{ matrix.binary }}-bin.txt
          # cp -r ${{ matrix.binary }}-bin.txt artifacts/

    outputs:
      binaries: ${{ steps.build.outputs.binaries }}

  test:
    name: Test ${{ matrix.name }} binaries
    runs-on: ${{ matrix.runner }}
    needs: build

    strategy:
      matrix:
        include:
          - name: Linux x64
            binary: linux-x64
            runner: rust
            target_os: linux
          - name: macOS aarch64 (Apple Silicon)
            binary: macos-x64
            runner: macos-14
            target_os: darwin

    steps:
      - id: test
        name: Test binaries
        run: |
          echo "test"
          echo "binaries: ${{ needs.build.outputs.binaries }}" >> ${{ matrix.binary }}-test.txt
